name: Deployment
on:
  release:
    types: [published]
jobs:
  generate-portable-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven
      - name: Parse version tag
        id: parse-tag
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "version=${TAG#v}" >> "$GITHUB_OUTPUT"
      - name: Building and packaging
        run: mvn compile package
      - name: Generate portable archive
        run: |
          cd jarmemu-distribution/target
          zip -r JArmEmu-${{ steps.parse-tag.outputs.version }}.zip ./jarmemu/
      - name: Compute SHA256 checksum
        id: sha256
        run: echo "sum=$(sha256sum JArmEmu-${{ steps.parse-tag.outputs.version }}.zip | awk '{print $1}')"
      - name: Upload portable archive to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: 'jarmemu-distribution/target/JArmEmu-${{ steps.parse-tag.outputs.version }}.zip'
    outputs:
      version: ${{ steps.parse-tag.outputs.version }}
      sum: ${{ steps.sha256.outputs.sum }}

  deploy-to-aur:
    runs-on: ubuntu-latest
    needs: generate-portable-archive
    steps:
      - name: Clone packaging repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'Dwight-Studio'
          repository: 'JArmEmu-Packages'
      - name: Generate PKGBUILD
        env:
          VERSION: ${{needs.generate-portable-archive.outputs.version}}
          SUM: ${{needs.generate-portable-archive.outputs.sum}}
        run: |
          cd JArmEmu-Packages/arch
          VERSION=$VERSION SUM=$SUM envsubst '${VERSION} ${SUM}' < PKGBUILD_template > PKGBUILD
      - name: Publish package to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v3.0.1
        with:
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          pkgbuild: JArmEmu-Packages/arch/PKGBUILD
          pkgname: 'jarmemu'
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update to v${{needs.generate-portable-archive.outputs.version}}