name: Validation
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check root project version
      uses: avides/actions-project-version-check@v1.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file-to-check: pom.xml
    - name: Check base version
      uses: avides/actions-project-version-check@v1.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file-to-check: jarmemu-base/pom.xml
    - name: Check distribution version
      uses: avides/actions-project-version-check@v1.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file-to-check: jarmemu-distribution/pom.xml
    - name: Check launcher version
      uses: avides/actions-project-version-check@v1.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file-to-check: jarmemu-launcher/pom.xml
    - name: Check medias version
      uses: avides/actions-project-version-check@v1.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file-to-check: jarmemu-medias/pom.xml

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven
      - name: Run tests
        run: mvn compile test